import { createApp } from 'vue';
import { createPinia } from 'pinia';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

/* ── Font Awesome ── */
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faPenToSquare,
  faPaperPlane,
  faThumbtack,
  faHeart as fasHeart,
  faCommentDots,
  faFilePen,
  faWandMagicSparkles,
  faXmark,
  faCalendarDays,
  faUsers,
  faCamera,
  faRobot,
  faShieldHalved,
  faGlobe,
  faLock,
  faChartBar,
  faCloud,
  faIdCard,
  faGears,
  faBuilding,
  faScrewdriverWrench,
  faChartLine,
  faPlus,
  faLink,
  faVideo,
  faRightFromBracket,
  faGear,
  faStar,
  faCirclePlus,
  faArrowRight,
  faArrowUpRightFromSquare,
  faLocationDot,
  faMap,
  faMapLocationDot,
  faChevronUp,
  faChevronRight,
  faCircleRight,
  faCirclePlay,
  faQrcode,
  faTriangleExclamation,
  faCircleExclamation,
  faBan,
  faClipboardCheck,
  faUserCheck,
  faImage,
  faImages,
  faMagnifyingGlassPlus,
  faCircleInfo,
  faUpload,
  faHotel,
  faBus,
  faUtensils,
  faWifi,
  faLaptop,
  faSignsPost,
  faSuitcaseRolling,
  faTags,
  faBullhorn,
  faClockRotateLeft,
  faComments,
  faSliders,
  faBars,
  faGripVertical,
  faIcons,
  faLightbulb,
  faSun,
  faCloudSun,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudBolt,
  faCloudSunRain,
  faCloudMoon,
  faSnowflake,
  faSmog,
  faWind,
  faTemperatureHigh,
  faTemperatureLow,
  faDroplet,
  faMoon,
  faQuestion,
  /* ── admin emoji → FA replacements ── */
  faFileImport,
  faFileArrowUp,
  faFileArrowDown,
  faCheck,
  faMusic,
  faUser,
  faCar,
  faHospital,
  faGamepad,
  faCompass,
  faFont,
  faFlask,
  faCartShopping,
  faShareNodes,
  faBuildingColumns,
  faBox,
  faEnvelope,
  faSchool,
  faCheckDouble,
  faFaceMeh,
  faMagnifyingGlass,
  faPaperclip,
  faFile,
  faFilePdf,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faFileImage,
  faFileZipper,
  faFileLines,
  faFileCsv,
  faFileAudio,
  faFileVideo,
  faFolderOpen,
  faFloppyDisk,
  faSpinner,
  faCircleCheck,
  faCircleXmark,
} from '@fortawesome/free-solid-svg-icons';
import {
  faHeart as farHeart,
  faComment as farComment,
  faTrashCan as farTrashCan,
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faPenToSquare,
  faPaperPlane,
  faThumbtack,
  fasHeart,
  farHeart,
  faCommentDots,
  farComment,
  faFilePen,
  faWandMagicSparkles,
  faXmark,
  faCalendarDays,
  faUsers,
  faCamera,
  faRobot,
  faShieldHalved,
  faGlobe,
  faLock,
  faChartBar,
  faCloud,
  faIdCard,
  faGears,
  faBuilding,
  faScrewdriverWrench,
  faChartLine,
  faPlus,
  faLink,
  faVideo,
  faRightFromBracket,
  faGear,
  faStar,
  faCirclePlus,
  faArrowRight,
  faArrowUpRightFromSquare,
  faLocationDot,
  faMap,
  faMapLocationDot,
  faChevronUp,
  faChevronRight,
  faCircleRight,
  faCirclePlay,
  faQrcode,
  faTriangleExclamation,
  faCircleExclamation,
  faBan,
  faClipboardCheck,
  faUserCheck,
  faImage,
  faImages,
  faMagnifyingGlassPlus,
  faCircleInfo,
  faUpload,
  faHotel,
  faBus,
  faUtensils,
  faWifi,
  faLaptop,
  faSignsPost,
  faSuitcaseRolling,
  faTags,
  faBullhorn,
  faClockRotateLeft,
  faComments,
  faSliders,
  faBars,
  faGripVertical,
  faIcons,
  faLightbulb,
  faSun,
  faCloudSun,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudBolt,
  faCloudSunRain,
  faCloudMoon,
  faSnowflake,
  faSmog,
  faWind,
  faTemperatureHigh,
  faTemperatureLow,
  faDroplet,
  faMoon,
  faQuestion,
  /* ── admin emoji → FA replacements ── */
  faFileImport,
  faFileArrowUp,
  faFileArrowDown,
  faCheck,
  faMusic,
  faUser,
  faCar,
  faHospital,
  faGamepad,
  faCompass,
  faFont,
  faFlask,
  faCartShopping,
  faShareNodes,
  faBuildingColumns,
  faBox,
  faEnvelope,
  faSchool,
  faCheckDouble,
  faFaceMeh,
  faMagnifyingGlass,
  farTrashCan,
  faPaperclip,
  faFile,
  faFilePdf,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faFileImage,
  faFileZipper,
  faFileLines,
  faFileCsv,
  faFileAudio,
  faFileVideo,
  faFolderOpen,
  faFloppyDisk,
  faSpinner,
  faCircleCheck,
  faCircleXmark,
);

import App from './App.vue';
import router from './router';
import { useAuthStore } from './stores/auth';
import './assets/main.css';

const app = createApp(App);

app.component('font-awesome-icon', FontAwesomeIcon);
app.use(createPinia());
app.use(router);
app.use(ElementPlus);

// hydrate auth from localStorage before mount
const auth = useAuthStore();
auth.hydrate();

app.mount('#app');
